[package]
name = "map_struct"
version = "0.1.0"
authors = ["Hajime Fukuda <hajime.fukuda@me.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
description = "A rust library to map raw data to a struct."

[dependencies]
